### ISSUE TITLE
Checkboxes in Fetch Data tab unclear

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#36]
In the current version of bfit on muesli the fit button in the Fetch Data tab does not appear to be working.

**Comment by vkarner** [comment]
It appears as if it is working, but just extremely slow and took many attempts.

**Comment by dfujim** [comment]
Global fitting can be slow with a poor set of initial parameters. Fit individually first, then set result as P0, then do the global fitting for faster results. Individual fitting shows the fit progress in the terminal.

**Comment by vkarner** [comment]
It is not the global fitting that I am having an issue with. After I fetch the run; I can draw it, set the binning etcetera. But then if I want to select some of the fetched runs to fit the Fit checkbox is appearing greyed out and is not clickable.

**Comment by dfujim** [comment]
The workflow is designed as follows: 

* Fetch Data tab: select the data you want, and view fit results. This tab does not do any fitting for you. You can't click the fit checkbox because there is no fit yet. 
* Fit Data tab: choose fitting function and do the fitting. The fit button in this tab is the one that will do the fitting. Once this is pressed, the fit will run and the checkbox in the Fetch Data tab will become un-greyed. 

Please let me know if this is not your issue.

**Comment by vkarner** [comment]
I see. I thought that was how you chose the subset of runs to fit. What if I fetch a large quantity of runs initially intending to fit all of them, but then you want to focus on a few specific temperatures to hammer out the global fit function parameters before fitting all of them.

**Comment by dfujim** [comment]
The leftmost checkbox is the one you want (left of the year). It's currently unlabelled, and I see that that this left things unclear. I will find some way of making the layout clearer.

**Comment by vkarner** [comment]
Sorry about that. It has been a long time since I have used your software, but it is very smooth. I like the global fitting. Is there a way of getting a global chi squared?

**Comment by dfujim** [comment]
No, your confusion is useful for keeping things clear for others! There is not, but I will add it to my to-do list.

**Comment by dfujim** [comment]
Improved clarity in commit 11fd5c769bf7834ca93275899bde8a593d0aa3cc
