### ISSUE TITLE
Ability to fill in CAMP or EPICS variables if they were not logging during run

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#70]
It would be nice to have the option to fill in CAMP or EPICS variables that were not logged during the run(s).

**Comment by dfujim** [comment]
Are you suggesting changes to the MUD files (which is not something I have permission to write to, nor would you want to in case of data corruption), or holding the info in memory? 

Alternatively, one could think of bfit starting a data file with all the user changes to the files, and apply them after loading, but this would be applicable only to you. 

A better plan might be to talk to Ben about implementing a post-run modification to his new DAQ so that the changes are permanent and shared across everyone.

**Comment by dfujim** [comment]
Resolved in e3438cec2624b7e4606c9d7cb07b955fc35fb30e
