### ISSUE TITLE
Bug with Legend

### ISSUE THREAD

**Issue by vkarner** [dfujim/bfit#71]
When I select Draw in New Window instead of the default Stack in existing window, the legend stops showing up.

**Comment by dfujim** [comment]
Can you give a trace of what you did to reproduce this result? 

Note that in order to prevent the legend size from becoming too large (and messing with the margins on the figure), the legend is automatically removed after the 9th run is drawn. The idea is that you probably wouldn't want to compare more than this and when you fit this is about as many items as the legend can handle before it starts obscuring what you're looking at. 

If you're doing online analysis then the mouseover text should help you id which run is which. Otherwise, you can always force the legend to show up by running "plt.legend()" in the "Run Commands" window found in the "File" menu.

**Comment by dfujim** [comment]
Resolved in 6ec8b06de9ebdbe93191b4e4bc8b8c250da019d1
