### ISSUE TITLE
Incorrect handling of beam pulse length when fitting SLR runs with different pulse durations

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bfit#85]
When fitting SLR runs with different beam pulse lengths, the pulse duration isn't handled correctly - only a <i>single</i> value is used for all runs. In the fit function, the value used appears to be the pulse length from the <i>last</i> run in the Fetch tab list, so I guess the parameter is getting overridden before it's passed to the function?

This can be reproduced with, for example, runs 41635-41637 from 2018 (corresponding to <sup>31</sup>Mg SLR data in MgO).

**Comment by dfujim** [comment]
Resolved in 3c29d57b4034198154ad4504a0c84a0b3f8d6b9a

The issue was [here](https://github.com/dfujim/bfit/blob/16b610bf01ef3757fdc26387f0d8860781742f8a/bfit/fitting/fitter.py#L274):

```python
fn.append(lambda x, *par : fa_31Mg(x, pulse)*fn1(x, *par))
```

where the lambda function pointer to `fn1`, which was the pulsed_* function, would just point to the last function created, rather than saving the parameters in each iteration as we loop over the runs. 

I also noticed that my implementation does not take into account the beam rate, using the default value of 1e-6, but I think this is a separate issue. 

Also, for completeness, the year should be 2016 in your suggested runs.
