### ISSUE TITLE
Missing exported parameters

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bfit#86]
When exporting fit parameters using the GUI, when one or more of the logged variables are missing for a subset of runs (e.g., platform bias, etc.), the affected (and derived) parameters appear to be omitted for <i>all runs</i> in the generated `.csv` (i.e., the data column is completely absent). Is this the intended behaviour?

Wouldn't it be better to export all values, replacing the suspect ones with, for example, `NaN`s or `None`s?

**Comment by dfujim** [comment]
This is definitely not the intended behaviour. Columns are only meant to be dropped if the entire column is reported to be `NaN`, which is to say that the variable is missing from all the runs. 

I suspect this is due to a difference in how we're reading/writing the csv file. When written, missing entries are not replaced by `NaN`, rather they are just missing. I didn't think this to be a problem since pandas.read_csv and the LIbreOffice importer both handle this fine, with pandas reporting in the manner you've suggested. 

Example:  
1. Fitting run 40123
2. Loading run 40127
3. Export

The resulting csv has a 1/T1 value reported for 40123, and nothing for 40127 (blank entry).

**Comment by rmlmcfadden** [comment]
Hmm, perhaps the problem is with the handling of the <i>logged variables</i> vs. the fit parameters - your example works as expected.

Reproducer of my issue:

- Load runs 40128-40144 from 2017.
- Fit to a single exponential (or anything really).
- Export the results.

In the output `.csv`, you'll see that (among others) `Impl. Energy (keV)` is missing, even through there is only a single run without a logged platform bias (40136).

Upon un-checking the culprit run in the Fetch tab and re-fitting/exporting, the missing columns now appear in the output.

**Comment by dfujim** [comment]
Ah yes, the downsides of using list comprehensions. 

This may not be the most elegant fix, but I believe this resolves the problem: d6f2f3a0e2774b3e68208233df1989a43df17a3b
